services:
  ddns-go:
    image: jeessy/ddns-go:latest
    container_name: ddnsgo
    network_mode: "container:mihomo"
    restart: always
    volumes:
      - ./:/root

networks:
  macvlan:
    external: true